INSERT INTO USER (USERNAME, PASSWORD, USER_TYPE) VALUES ('user1', '$2a$10$w3Rt.2zXfXMN0IG0vB5Fvur9gl07w5q7VB/aYy2aN8ChHDwixZzly', 'REGULAR');
INSERT INTO USER (USERNAME, PASSWORD, USER_TYPE) VALUES ('user2', '$2a$10$qNttw7hkELIJaDd7vczMze07ydfgcvCZNWeIDQ/Ei4V5Vg4drwwAu', 'REGULAR');
INSERT INTO USER (USERNAME, PASSWORD, USER_TYPE) VALUES ('admin1', '$2a$10$Hr5E3gaALbGaLaFgL6KVkeKKX7tHHimzF3TlHsedSkK6fDTxkJsdO', 'ADMIN');
INSERT INTO USER (USERNAME, PASSWORD, USER_TYPE) VALUES ('admin2', '$2a$10$NDOXOE7DSPeKt4kBNHCbJeik.Wl3Zdro9zFTayTr1LlzONFnzKDRO', 'ADMIN');
INSERT INTO ITEM (NAME, DESCRIPTION, START_PRICE, DATE_END) VALUES ('Item1', 'Dummy item number one for auction.', 10, '20210520');
INSERT INTO BID (USER_ID, BID_PRICE) VALUES (1, 10);
INSERT INTO ITEM_BIDS (ITEM_ID, BIDS_ID) VALUES (1, 1);