INSERT INTO USER (USERNAME, PASSWORD, USER_TYPE) VALUES ('user1', 'user1', 'REGULAR');
INSERT INTO USER (USERNAME, PASSWORD, USER_TYPE) VALUES ('user2', 'user2', 'REGULAR');
INSERT INTO USER (USERNAME, PASSWORD, USER_TYPE) VALUES ('admin1', 'admin1', 'ADMIN');
INSERT INTO USER (USERNAME, PASSWORD, USER_TYPE) VALUES ('admin2', 'admin2', 'ADMIN');
INSERT INTO ITEM (NAME, DESCRIPTION, START_PRICE, DATE_END) VALUES ('Item1', 'Dummy item number one for auction.', 10, '20210520');
INSERT INTO BID (USER_ID, BID_PRICE) VALUES (1, 10);
INSERT INTO ITEM_BIDS (ITEM_ID, BIDS_ID) VALUES (1, 1);